---
abstract: 'SMTP client and server'
author:
  - 'Mons Anderson <mons@cpan.org>'
build_requires:
  Test::More: 0
  lib::abs: 0.90
distribution_type: module
generated_by: 'Module::Install version 0.71'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: AnyEvent-SMTP
no_index:
  directory:
    - inc
    - t
requires:
  AnyEvent: 4.82
  Mail::Address: 0
  Object::Event: 1.0
  Sys::Hostname: 0
  common::sense: 0
version: 0.06
